#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Scaleup Technologies
- Sven Anders (@tabacha)
description: Gets C__CATS__LAYER2_NET category  values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
module: idoit_cat_layer2_net_info
options: {}
short_description: Get values from a layer2_net category to an object

'''

EXAMPLES = r'''
name: Search for a category for object 1320
scaleuptechnologies.idoit.idoit_cat_layer2_net_info:
  idoit: '{{ idoit_access }}'
  obj_id: 1320

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: Data of the category
  returned: always
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATS__LAYER2_NET
fields:
  description:
    description: Description of the Layer2 Net
    type: html
  standard:
    description: Standard VLAN
    type: bool
  subtype:
    description: Subtype
    description_id: Id of Subtyp
    type: dialog
  type:
    description: Typ
    description_id: Id of Typ
    type: dialog
  vlan_id:
    description: VLAN Id
    type: str
  vrf:
    description: VRF
    type: str
  vrf_capacity:
    description: VRF Capacity
    type: int
  vrf_capacity_unit:
    description: Unit of the vrf_capacity (bit/s,kbit/s,Mbit/s,Gbit/s)
    description_id: Id of vrf_capacity unit
    type: dialog
single_value_cat: true

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryInfoModule
import yaml


def run_module():
    module = IdoitCategoryInfoModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
