#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__GLOBAL category to an object if not there or
  update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.single_category_options
module: idoit_cat_global
options:
  category:
    description: Category
    type: str
  category_id:
    description: Category of the Object
    type: int
  description:
    description: Description
    type: str
  purpose:
    description: Purpose
    type: str
  purpose_id:
    description: Purpose of the Object
    type: int
  status:
    description: Status
    type: str
  status_id:
    description: Id of Status
    type: int
  sysid:
    description: SYS-ID
    type: str
  title:
    description: Title
    type: str
short_description: Create or update a global category to an object

'''

EXAMPLES = r'''
- name: Set a new Name
  scaleuptechnologies.idoit.idoit_cat_global:
    idoit: '{{ idoit_access }}'
    obj_id: 1320
    state: merge
    title: my_machine.int.yco.de

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__GLOBAL
fields:
  category:
    description: Category
    description_id: Category of the Object
    type: dialog
  description:
    description: Description
    type: html
  purpose:
    description: Purpose
    description_id: Purpose of the Object
    type: dialog
  status:
    description: Status
    description_id: Id of Status
    type: dialog
  sysid:
    description: SYS-ID
    type: str
  title:
    description: Title
    type: str
single_value_cat: true

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
