#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__POWER_CONSUMER category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_power_consumer
options:
  active:
    description: Active
    type: bool
  ampere:
    description: Ampere
    type: float
  btu:
    description: British thermal unit
    type: str
  description:
    description: Description of the Power Consumer
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    type: str
  manufacturer_id:
    description: Id of Manufactuerer of the device
    type: int
  model:
    description: Model of the device, if not there it will be created
    type: str
  model_id:
    description: Id of Model of the device
    type: int
  title:
    description: Title
    type: str
  volt:
    description: Voltage
    type: float
  watt:
    description: Watt
    type: float
short_description: Create or update a power_consumer category to an object

'''

EXAMPLES = r'''
- name: Set a new Memory Module
  scaleuptechnologies.idoit.idoit_power_consumer:
    id: 2
    idoit: '{{ idoit_access }}'
    manufacturer: Dell
    obj_id: 1320
    title: Slot 1
    volt: 230
    watt: 550.0

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__POWER_CONSUMER
fields:
  active:
    default: false
    description: Active
    type: bool
  ampere:
    description: Ampere
    type: float
  btu:
    description: British thermal unit
    type: str
  description:
    description: Description of the Power Consumer
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    description_id: Id of Manufactuerer of the device
    type: dialog
  model:
    description: Model of the device, if not there it will be created
    description_id: Id of Model of the device
    dialog_parent: manufacturer
    type: dialog
  title:
    description: Title
    type: str
  volt:
    description: Voltage
    type: float
  watt:
    description: Watt
    type: float
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit_api.consts as consts
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
