#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__NETWORK_PORT category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_net_port
options:
  active:
    description: Active
    type: bool
  addresses:
    description: Ids of the Adress Object-id
    elements: int
    type: list
  cable_id:
    description: Id of the Cable
    type: int
  default_vlan_id:
    description: Standard VLAN
    type: int
  description:
    description: Description of the Model
    type: str
  duplex_id:
    description: Id of the duplex (1=Half, 2=Full)
    type: int
  hba_id:
    description: Id of the HBA
    type: int
  interface_id:
    description: Id of the net_interface
    type: int
  mac:
    description: MAC-address
    type: str
  mtu:
    description: MTU (Maximum Transfer Unit)
    type: str
  negotiation_id:
    description: Id of the negotiation (1=Automatic, 2=Manuell)
    type: int
  plug_type:
    description: Plug Type (RJ-45,RJ-11, LC, SC)
    type: str
  plug_type_id:
    description: Id of the Plug Type
    type: int
  port_mode:
    description: Mode (Standard, Stacking, Link Aggregation/Trunk)
    type: str
  port_mode_id:
    description: Id of the Mode
    type: int
  port_type:
    description: Type (Ethernet, FR, ISDN, ...)
    type: str
  port_type_id:
    description: Id of the Type
    type: int
  speed:
    description: Speed of the Interface
    type: float
  speed_type:
    description: Unit of the Speed (bit/s,kbit/s,Mbit/s,Gbit/s)
    type: str
  speed_type_id:
    description: Id of Speed Unit
    type: int
  standard:
    description: Standard
    type: str
  standard_id:
    description: Id of Strandard
    type: int
  title:
    description: Title
    type: str
short_description: Create or update a net_port category to an object

'''

EXAMPLES = r'''
- name: Set Network Port
  scaleuptechnologies.idoit.idoit_cat_net_port:
    idoit: '{{ idoit_access_test }}'
    mac: C8:1F:66:CA:29:51
    obj_id: 4005
    plug_type: RJ-45
    search_by_fields:
    - title
    state: merge
    title: eth0

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__NETWORK_PORT
fields:
  active:
    default: true
    description: Active
    type: bool
  addresses:
    description: Ids of the Adress Object-id
    element_type: int
    type: list
  cable:
    ansible_name: cable_id
    description: Id of the Cable
    type: int
  default_vlan:
    ansible_name: default_vlan_id
    description: Standard VLAN
    type: int
  description:
    description: Description of the Model
    type: html
  duplex:
    ansible_name: duplex_id
    default: 2
    description: Id of the duplex (1=Half, 2=Full)
    type: int
  hba:
    ansible_name: hba_id
    description: Id of the HBA
    type: int
  interface:
    ansible_name: interface_id
    description: Id of the net_interface
    type: int
  mac:
    description: MAC-address
    type: str
  mtu:
    default: '1500'
    description: MTU (Maximum Transfer Unit)
    type: str
  negotiation:
    ansible_name: negotiation_id
    default: 1
    description: Id of the negotiation (1=Automatic, 2=Manuell)
    type: int
  plug_type:
    description: Plug Type (RJ-45,RJ-11, LC, SC)
    description_id: Id of the Plug Type
    type: dialog
  port_mode:
    description: Mode (Standard, Stacking, Link Aggregation/Trunk)
    description_id: Id of the Mode
    type: dialog
  port_type:
    description: Type (Ethernet, FR, ISDN, ...)
    description_id: Id of the Type
    type: dialog
  speed:
    description: Speed of the Interface
    type: float
  speed_type:
    description: Unit of the Speed (bit/s,kbit/s,Mbit/s,Gbit/s)
    description_id: Id of Speed Unit
    type: dialog
  standard:
    description: Standard
    description_id: Id of Strandard
    type: dialog
  title:
    description: Title
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
