#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__APPLICATION category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_application
options:
  application:
    description: Software Id
    type: int
  application_priority:
    description: Application Priority
    type: str
  application_priority_id:
    description: Assigned Priority Id (1=Primary, 2=Secondary)
    type: int
  assigned_version:
    description: Assigned Version
    type: str
  assigned_version_id:
    description: Assigned Version Id
    type: int
  description:
    description: Description of the Assingment
    type: str
  installDate:
    description: Installation Date
    type: str
short_description: Create or update a application category to an object

'''

EXAMPLES = r'''
[]

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__APPLICATION
fields:
  application:
    description: Software Id
    type: int
  application_priority:
    description: Application Priority
    description_id: Assigned Priority Id (1=Primary, 2=Secondary)
    type: dialog
  assigned_version:
    description: Assigned Version
    description_id: Assigned Version Id
    dialog_parent: application
    type: dialog
  description:
    description: Description of the Assingment
    type: html
  installDate:
    description: Installation Date
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
