#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__NETWORK_INTERFACE category to an object if not
  there or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_net_interface
options:
  description:
    description: Description of the Model
    type: str
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    type: str
  manufacturer_id:
    description: Id of Manufactuerer of the device
    type: int
  model:
    description: Model of the device, if not there it will be created
    type: str
  model_id:
    description: Id of Model of the device
    type: int
  serial:
    description: Serial number
    type: str
  slot:
    description: Slotnumber
    type: str
  title:
    description: Title
    type: str
short_description: Create or update a net_interface category to an object

'''

EXAMPLES = r'''
- name: Set Network Interface
  scaleuptechnologies.idoit.idoit_net_interface:
    idoit: '{{ idoit_access_test }}'
    manufacturer: Broadcom Corp
    model: Broadcom Gigabit Ethernet BCM5720
    obj_id: 4005
    search_by_fields:
    - title
    serial: C8 1F 66 CA 29 51
    slot: NIC.Embedded.1-1-1
    title: NIC.Embedded.1-1-1 C8 1F 66 CA 29 51

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__NETWORK_INTERFACE
fields:
  description:
    description: Description of the Model
    type: html
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    description_id: Id of Manufactuerer of the device
    type: dialog
  model:
    description: Model of the device, if not there it will be created
    description_id: Id of Model of the device
    type: dialog
  serial:
    description: Serial number
    type: str
  slot:
    description: Slotnumber
    type: str
  title:
    description: Title
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
