#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__ACCESS category to an object if not there or
  update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_access
options:
  description:
    description: Description of the Model
    type: str
  primary:
    description: Is this the primary access
    type: bool
  title:
    description: Title
    type: str
  type:
    description: Type of the Access
    type: str
  type_id:
    description: Id of the type
    type: int
  url:
    description: Url
    type: str
short_description: Create or update a access category to an object

'''

EXAMPLES = r'''
- name: Set a new Idrac
  scaleuptechnologies.idoit.idoit_cat_access:
    idoit: '{{ idoit_access }}'
    obj_id: 1320
    primary: false
    title: IDRAC
    type: BMC
    url: https://idrac-server1.example.org

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__ACCESS
fields:
  description:
    description: Description of the Model
    type: html
  primary:
    default: false
    description: Is this the primary access
    type: bool
  title:
    description: Title
    type: str
  type:
    description: Type of the Access
    description_id: Id of the type
    type: dialog
  url:
    description: Url
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
