#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__IDENTIFIER category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_identifier
options:
  description:
    description: Description
    type: str
  group:
    description: Group
    type: str
  key:
    description: Key
    type: str
  last_edited:
    description: Last edited
    type: str
  last_scan:
    description: Last scan
    type: str
  last_updated:
    description: Last updated
    type: str
  type:
    description: Type
    type: str
  type_id:
    description: Id of type
    type: int
  value:
    description: Value
    type: str
short_description: Create or update a identifier category to an object

'''

EXAMPLES = r'''
- name: Set a new Name
  scaleuptechnologies.idoit.idoit_cat_identifier:
    idoit: '{{ idoit_access }}'
    key: bad_crm_id
    last_edited: '2023-10-24 08:18:10'
    last_scan: '2023-10-24 08:20:00'
    last_updated: '2023-10-24 08:18:10'
    obj_id: 1320
    search_by_fields:
    - key
    type: BadCRM 2.0
    value: 19

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__IDENTIFIER
fields:
  description:
    description: Description
    type: html
  group:
    description: Group
    type: str
  key:
    description: Key
    type: str
  last_edited:
    description: Last edited
    type: date_hhmm
  last_scan:
    description: Last scan
    type: date_hhmm
  last_updated:
    description: Last updated
    type: date_hhmm
  type:
    description: Type
    description_id: Id of type
    type: dialog
  value:
    description: Value
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
