#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__NETWORK_LOG_PORT category to an object if not
  there or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_net_log_port
options:
  active:
    description: Active
    type: bool
  addresses:
    description: Ids of the Adress Object-id
    elements: int
    type: list
  description:
    description: Description of the Model
    type: str
  mac:
    description: MAC-address
    type: str
  parent:
    description: Parent
    type: str
  parent_id:
    description: Id of the parent
    type: int
  port_ids:
    description: Id of the port
    type: int
  port_type:
    description: Type
    type: str
  port_type_id:
    description: Id of the port_type
    type: int
  standard:
    description: Standard
    type: str
  standard_id:
    description: Id of Strandard
    type: int
  title:
    description: Title
    type: str
short_description: Create or update a net_log_port category to an object

'''

EXAMPLES = r'''
- name: Set Network Logical Port
  scaleuptechnologies.idoit.idoit_cat_net_log_port:
    idoit: '{{ idoit_access_test }}'
    mac: C8:1F:66:CA:29:51
    obj_id: 4005
    ports:
    - eth0
    - eth1
    search_by_fields:
    - title
    state: merge
    title: bond0

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__NETWORK_LOG_PORT
fields:
  active:
    default: true
    description: Active
    type: bool
  addresses:
    description: Ids of the Adress Object-id
    element_type: int
    type: list
  description:
    description: Description of the Model
    type: html
  mac:
    description: MAC-address
    type: str
  parent:
    description: Parent
    description_id: Id of the parent
    type: dialog
  port_type:
    description: Type
    description_id: Id of the port_type
    type: dialog
  ports:
    ansible_name: port_ids
    description: Id of the port
    type: int
  standard:
    description: Standard
    description_id: Id of Strandard
    type: dialog
  title:
    description: Title
    type: str
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
