#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__VIRTUAL_MACHINE category to an object if not
  there or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_virtual_machine
options:
  config_file:
    description: Config File
    type: str
  description:
    description: Description
    type: str
  hosts:
    description: Id of Host of the Virtual Machine
    type: int
  is_virtual:
    description: Is virtual? (2=Virtual, 3=Not Virtual)
    type: int
  system:
    description: Type of virtualization, Vmware, Hyper-V, OpenStack ...
    type: str
  system_id:
    description: Id of type of virtualization, Vmware, Hyper-V, OpenStack
      ...
    type: int
short_description: Create or update a virtual_machine category to an object

'''

EXAMPLES = r'''
- name: Set Virtual machine setting
  scaleuptechnologies.idoit.idoit_cat_virtual_machine:
    config_file: HalloDu.yml
    hosts: 3123
    idoit: '{{ idoit_access_test }}'
    is_virtual: 2
    obj_id: 16783
    system_id: 13

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__VIRTUAL_MACHINE
fields:
  config_file:
    description: Config File
    type: str
  description:
    description: Description
    type: html
  hosts:
    description: Id of Host of the Virtual Machine
    type: int
  system:
    description: Type of virtualization, Vmware, Hyper-V, OpenStack ...
    description_id: Id of type of virtualization, Vmware, Hyper-V, OpenStack
      ...
    type: dialog
  virtual_machine:
    ansible_name: is_virtual
    description: Is virtual? (2=Virtual, 3=Not Virtual)
    type: int
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
