#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Scaleup Technologies
- Sven Anders (@tabacha)
description: Gets C__CATG__VIRTUAL_MACHINE category  values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
module: idoit_cat_vritual_machine_info
options: {}
short_description: Get values from a vritual_machine category to an object

'''

EXAMPLES = r'''
name: Search for a category for object 1320
scaleuptechnologies.idoit.idoit_cat_vritual_machine_info:
  idoit: '{{ idoit_access }}'
  obj_id: 1320

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: Data of the category
  returned: always
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__VIRTUAL_MACHINE
fields:
  config_file:
    description: Config File
    type: str
  description:
    description: Description
    type: str
  hosts:
    description: Id of Host of the Virtual Machine
    type: int
  system:
    description: Type of virtualization, Vmware, Hyper-V, OpenStack ...
    description_id: Id of type of virtualization, Vmware, Hyper-V, OpenStack
      ...
    type: dialog
  vritual_machine:
    ansible_name: is_virtual
    description: Is virtual?
    type: bool
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryInfoModule
import yaml


def run_module():
    module = IdoitCategoryInfoModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
