#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Scaleup Technologies
- Sven Anders (@tabacha)
description: Gets C__CATG__MEMORY category  values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
module: idoit_cat_memory_info
options: {}
short_description: Get values from a memory category to an object

'''
EXAMPLES = r'''
name: Search for a category for object 1320
scaleuptechnologies.idoit.idoit_cat_memory_info:
  idoit: '{{ idoit_access }}'
  obj_id: 1320

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: Data of the category
  returned: always
  type: complex

'''
IDOIT_SPEC = r'''
category: C__CATG__MEMORY
fields:
  capacity:
    description: Type of the Memory DDR, DDR2, SDRAM ..
    type: float
  description:
    description: Description of the Memory Module
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will be created
    description_id: Id of Manufactuerer of the device
    type: dialog
  title:
    description: Something like MemoryStick, Flash, DDRAM, SDRAM, ..
    description_id: Id of title
    type: dialog
  unit:
    description: Unit of the capacity (B,KB,MB,GB,TB)
    description_id: Id of Capacity Unit
    type: dialog
single_value_cat: false

'''
from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryInfoModule
import ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit_api.consts as consts
import yaml


def run_module():
    module = IdoitCategoryInfoModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()

def main():
    run_module()

if __name__ == '__main__':
    main()