#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATS__PERSON_MASTER category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.single_category_options
module: idoit_cat_person_master
options:
  description:
    description: Description of the Power Consumer
    type: str
  first_name:
    description: First Name
    type: str
  function:
    description: Function
    type: str
  last_name:
    description: Last Name
    type: str
  mail:
    description: Mail
    type: str
  personnel_number:
    description: Personal Number
    type: str
  phone_company:
    description: Phone number in the office
    type: str
  phone_mobile:
    description: Mobile phone number
    type: str
  title:
    description: Title
    type: str
short_description: Create or update a person_master category to an object

'''

EXAMPLES = r'''
- name: Set stammdaten
  scaleuptechnologies.idoit.idoit_cat_person_master:
    first_name: Sven
    function: Head of Automatisation
    idoit: '{{ idoit_access }}'
    last_name: Anders
    obj_id: 26

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATS__PERSON_MASTER
fields:
  description:
    description: Description of the Power Consumer
    type: html
  first_name:
    description: First Name
    type: str
  function:
    description: Function
    type: str
  last_name:
    description: Last Name
    type: str
  mail:
    description: Mail
    type: str
  personnel_number:
    description: Personal Number
    type: str
  phone_company:
    description: Phone number in the office
    type: str
  phone_mobile:
    description: Mobile phone number
    type: str
  title:
    description: Title
    type: str
single_value_cat: true

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
