#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__IP category to an object if not there or update
  values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_ip
options:
  active:
    description: Is this the ip active
    type: bool
  assigned_port_id:
    description: Id of the assigned port
    type: int
  description:
    description: Description of the Model
    type: str
  dns_server_id:
    description: Id of the DNS Server
    type: int
  domain:
    description: Doamin
    type: str
  hostname:
    description: Hostname without Domain
    type: str
  ipv4_address:
    description: Ip Address
    type: str
  ipv4_assignment:
    description: Address sssignment (DHCP, DHCP reserved, Static, unnumberd)
    type: str
  ipv4_assignment_id:
    description: Id of the type
    type: int
  ipv6_address:
    description: Ip Address
    type: str
  ipv6_assignment:
    description: Address sssignment (DHCPv6, SLAAC)
    type: str
  ipv6_assignment_id:
    description: Id of the type
    type: int
  ipv6_scope:
    description: Address sssignment (Global unicast, Link Local, unique
      Local)
    type: str
  ipv6_scope_id:
    description: Id of the type
    type: int
  is_gateway:
    description: Is the default gateway of the network
    type: bool
  net_id:
    description: Id of the assigned Network
    type: int
  net_type:
    description: Net Type (AT, IPv4, IPv6, IPX)
    type: str
  net_type_id:
    description: Id of the type
    type: int
  primary:
    description: Is this the primary ip
    type: bool
  zone:
    description: Zone
    type: str
  zone_id:
    description: Id of the zone
    type: int
short_description: Create or update a ip category to an object

'''

EXAMPLES = r'''
- name: Set a new Idrac
  scaleuptechnologies.idoit.idoit_cat_ip:
    idoit: '{{ idoit_access }}'
    ipv4_address: 192.168.11.2
    net_type: IPv4
    obj_id: 1320
    primary: false

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__IP
fields:
  active:
    default: false
    description: Is this the ip active
    type: bool
  assigned_port:
    ansible_name: assigned_port_id
    description: Id of the assigned port
    type: int
  description:
    description: Description of the Model
    type: html
  dns_server:
    ansible_name: dns_server_id
    description: Id of the DNS Server
    type: int
  domain:
    description: Doamin
    type: str
  hostname:
    description: Hostname without Domain
    type: str
  ipv4_address:
    description: Ip Address
    type: str
  ipv4_assignment:
    description: Address sssignment (DHCP, DHCP reserved, Static, unnumberd)
    description_id: Id of the type
    type: dialog
  ipv6_address:
    description: Ip Address
    type: str
  ipv6_assignment:
    description: Address sssignment (DHCPv6, SLAAC)
    description_id: Id of the type
    type: dialog
  ipv6_scope:
    description: Address sssignment (Global unicast, Link Local, unique
      Local)
    description_id: Id of the type
    type: dialog
  net:
    ansible_name: net_id
    description: Id of the assigned Network
    type: int
  net_type:
    description: Net Type (AT, IPv4, IPv6, IPX)
    description_id: Id of the type
    type: dialog
  primary:
    default: false
    description: Is this the primary ip
    type: bool
  use_standard_gateway:
    ansible_name: is_gateway
    default: false
    description: Is the default gateway of the network
    type: bool
  zone:
    description: Zone
    description_id: Id of the zone
    type: dialog
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
