#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__STORAGE_DEVICE category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_storage_device
options:
  capacity:
    description: Capacity of the device
    type: float
  controller_id:
    description: Id of the controller
    type: int
  description:
    description: Description
    type: str
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    type: str
  manufacturer_id:
    description: Id of Manufactuerer of the device
    type: int
  model:
    description: Model of the device, if not there it will be created
    type: str
  model_id:
    description: Id of Model of the device
    type: int
  serial:
    description: Serial number
    type: str
  title:
    description: Title
    type: str
  type:
    description: Type of the Device like CD/DVD-ROM, Floppy Drive, Hard
      Drive, SSD, ..
    type: str
  type_id:
    description: Id of the type
    type: int
  unit:
    description: Memory unit of the capacity like B, KB, MB, TB, GB
    type: str
  unit_id:
    description: Id of the memory unit
    type: int
short_description: Create or update a storage_device category to an object

'''

EXAMPLES = r'''
- name: Set a new Disk
  scaleuptechnologies.idoit.idoit_cat_storage_device:
    capacity: 250
    firmware: 21.3.4-0001
    idoit: '{{ idoit_access }}'
    manufacturer: Samsung
    model: SM2300
    obj_id: 1320
    title: Slot 1,2
    type: SSD
    unit: GB

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__STORAGE_DEVICE
fields:
  capacity:
    description: Capacity of the device
    type: float
  controller:
    ansible_name: controller_id
    description: Id of the controller
    type: int
  description:
    description: Description
    type: str
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    description_id: Id of Manufactuerer of the device
    type: dialog
  model:
    description: Model of the device, if not there it will be created
    description_id: Id of Model of the device
    dialog_parent: manufacturer
    type: dialog
  serial:
    description: Serial number
    type: str
  title:
    description: Title
    type: html
  type:
    description: Type of the Device like CD/DVD-ROM, Floppy Drive, Hard
      Drive, SSD, ..
    description_id: Id of the type
    type: dialog
  unit:
    description: Memory unit of the capacity like B, KB, MB, TB, GB
    description_id: Id of the memory unit
    type: dialog
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
