#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATS__LAYER2_NET category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.single_category_options
module: idoit_cat_layer2_net
options:
  description:
    description: Description of the Layer2 Net
    type: str
  standard:
    description: Standard VLAN
    type: bool
  subtype:
    description: Subtype
    type: str
  subtype_id:
    description: Id of Subtyp
    type: int
  type:
    description: Typ
    type: str
  type_id:
    description: Id of Typ
    type: int
  vlan_id:
    description: VLAN Id
    type: str
  vrf:
    description: VRF
    type: str
  vrf_capacity:
    description: VRF Capacity
    type: int
  vrf_capacity_unit:
    description: Unit of the vrf_capacity (bit/s,kbit/s,Mbit/s,Gbit/s)
    type: str
  vrf_capacity_unit_id:
    description: Id of vrf_capacity unit
    type: int
short_description: Create or update a layer2_net category to an object

'''

EXAMPLES = r'''
- name: Create a new VLAN
  scaleuptechnologies.idoit.idoit_cat_layer2_net:
    id: 2
    idoit: '{{ idoit_access }}'
    obj_id: 1320
    title: Customer 70142 [42]
    vlan_id: 42

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATS__LAYER2_NET
fields:
  description:
    description: Description of the Layer2 Net
    type: html
  standard:
    description: Standard VLAN
    type: bool
  subtype:
    description: Subtype
    description_id: Id of Subtyp
    type: dialog
  type:
    description: Typ
    description_id: Id of Typ
    type: dialog
  vlan_id:
    description: VLAN Id
    type: str
  vrf:
    description: VRF
    type: str
  vrf_capacity:
    description: VRF Capacity
    type: int
  vrf_capacity_unit:
    description: Unit of the vrf_capacity (bit/s,kbit/s,Mbit/s,Gbit/s)
    description_id: Id of vrf_capacity unit
    type: dialog
single_value_cat: true

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
