#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__MODEL category to an object if not there or update
  values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.single_category_options
module: idoit_cat_model
options:
  description:
    description: Description of the Model
    type: str
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    type: str
  manufacturer_id:
    description: Id of Manufactuerer of the device
    type: int
  model:
    description: Model of the device, if not there it will be created
    type: str
  model_id:
    description: Id of Model of the device
    type: int
  product_id:
    description: Product-ID
    type: str
  serial:
    description: Serial
    type: str
  service_tag:
    description: Service Tag
    type: str
short_description: Create or update a model category to an object

'''

EXAMPLES = r'''
- name: Set a Model for a machine with serial
  scaleuptechnologies.idoit.idoit_cat_model:
    idoit: '{{ idoit_access }}'
    manufacturer: HP
    model: ProLiant DL160G6
    obj_id: 1320
    serial: '42'
    service_tag: CZJ037040C

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__MODEL
fields:
  description:
    description: Description of the Model
    type: html
  firmware:
    description: Firmware
    type: str
  manufacturer:
    description: Name of Manufactuerer of the device, if not there it will
      be created
    description_id: Id of Manufactuerer of the device
    type: dialog
  productid:
    ansible_name: product_id
    description: Product-ID
    type: str
  serial:
    description: Serial
    type: str
  service_tag:
    description: Service Tag
    type: str
  title:
    ansible_name: model
    description: Model of the device, if not there it will be created
    description_id: Id of Model of the device
    dialog_parent: manufacturer
    type: dialog
single_value_cat: true

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
