#!/usr/bin/python

# Autogenerated by build.py DO NOT EDIT HERE

# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type


DOCUMENTATION = r'''
author:
- Sven Anders (during work by ScaleUp Technologies) (@tabacha)
description: Adds C__CATG__CONNECTOR category to an object if not there
  or update values
extends_documentation_fragment:
- scaleuptechnologies.idoit.idoit_option
- scaleuptechnologies.idoit.category_options
- scaleuptechnologies.idoit.multi_category_options
module: idoit_cat_connector
options:
  connection_type:
    description: Schuko, ...
    type: str
  connection_type_id:
    description: Id of connection_type
    type: int
  connector_sibling:
    description: Assinged Input or Output id
    type: int
  description:
    description: Description of the Model
    type: str
  in_or_output:
    description: input (1) or output (2)
    type: int
  interface:
    description: Speed of the interface
    type: str
  interface_id:
    description: Id of Interface
    type: int
  title:
    description: Title
    type: str
short_description: Create or update a connector category to an object

'''

EXAMPLES = r'''
- name: Set a new Power Port
  scaleuptechnologies.idoit.idoit_cat_connector:
    connection_type: Schuko
    idoit: '{{ idoit_access }}'
    in_or_output: 1
    obj_id: 1320
    title: '01'

'''

RETURN = r'''
changed:
  description: Are there changes?
  returned: always
  type: bool
data:
  description: New data
  sample:
    description: ''
    firmware: ''
    manufacturer_id: 5
    model_id: 22
    product_id: ''
    serial: Test 42
    service_tag: CZJ037040C
  type: complex
id:
  description: Category Id of the saved category
  type: int
return:
  description: I-Doit API Result
  type: complex

'''

IDOIT_SPEC = r'''
category: C__CATG__CONNECTOR
fields:
  connection_type:
    description: Schuko, ...
    description_id: Id of connection_type
    type: dialog
  connector_sibling:
    description: Assinged Input or Output id
    type: int
  description:
    description: Description of the Model
    type: html
  interface:
    description: Speed of the interface
    description_id: Id of Interface
    type: dialog
  title:
    description: Title
    type: str
  type:
    ansible_name: in_or_output
    description: input (1) or output (2)
    type: int
single_value_cat: false

'''

from ansible_collections.scaleuptechnologies.idoit.plugins.module_utils.idoit import IdoitCategoryModule
import yaml


def run_module():
    module = IdoitCategoryModule(
        idoit_spec=yaml.safe_load(IDOIT_SPEC),
    )
    module.run()


def main():
    run_module()


if __name__ == '__main__':
    main()
